version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./local_nginx.conf:/etc/nginx/nginx.conf
    networks:
      default:
        ipv4_address: 172.25.0.3
    links:
      - php
  php:
    build: './'
    volumes:
      - ./:/var/www/html

networks:
  default:
    ipam:
      config:
        - subnet: 172.25.0.0/24